[package]
name = "ray-tracing-in-1-weekend"
version = "0.1.0"
authors = ["Daniel Prilik <danielprilik@gmail.com>"]
edition = "2018"

[dependencies]
minifb = "0.12.0"
num_cpus = "1.10.1"
rand = "0.7.0"
cfg-if = "0.1.9"

[features]
enum_dispatch = []
default = []
